language: node_js
node_js:
- '4'
env:
  global:
  - CXX=g++-4.8
  - DEPLOY_BRANCH=master
  - secure: FmsNRi1F6hV1LJY3EmlyxU6vlaqZjpjMC+9RAAxcCD9I4PDOFR74VKM7BIkfNN1X+aB2oJLcSOHaVMAzYdJKcFuk70TIUzsASvWiqo84RvBnnOhqOYC9+sr+r8ogmOKo4KZfF50uihYfciZh2945cSTiWEfJrpYZ8Z6Jt60u/VcqTKvOVRl9UASvri3Jjx1h3U/Tysljh52+4OWJjlzzfElHRwdNrxt9m4zqJEovW9TjaATEAmwaR+6DCHa4G8H1Ib08BAeX7wv9XXY+YxwWpykEb5i+akfyu2ZxABFBvO06iD0vhF5Qub9qiFRrmFz/gk18e0IRO+lbOOo8UP6fNBXT6WexPw9U/4wr5nqCEEgY8HZLBKxn1sPpuuJBbb7ryiaSse8zWz+QfA/vRpC7+6DFKw5jW02cHXdvhqcJvn9iqOJpOYR55wUMGqcwLouWR7/SexiJyuuy6yugrjuytT4/BvtW2/Vq7uUxBWqyCcZF0RWEK7yCZ34tH3VKbtpB2o9U77rU/gPehumLLzzJ2zNVePNp+zHPdx9+9WC0CVSkv/qj9uhHdx0tXbFf5ZCj/OYiA42CBuTf1rUlemmaTNVJruztEpLWjA4/FJwY1c+/k9th1eNnhtSJBXzonNhufRyJSebIamTloyGMzB9I6t5bV62lwfzR3yR7nB6mvSg=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  apt: true
  directories:
  - node_modules
before_install:
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/lint.sh
before_script:
- "./.build_scripts/lint.sh"
- npm test
script:
- npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: ".build_scripts/deploy.sh"
  on:
    branch: "${DEPLOY_BRANCH}"
