language: node_js
node_js:
- '4'
env:
  global:
  - CXX=g++-4.8
  - DEPLOY_BRANCH=master
  - secure: SuyTQvOdcSQSWBaBSwxGA5XuI/ZfDov1yfXx1F7Agvzu4WRRTa/5en3CxdjOymHNBlZdyHJMyf08x+0bDstlUxLZViEYX6XoJKZwGq+CtWKU3ANtfa9k6ONnGsfTD70ds/Hipsfj64nofbMbttBLAh1DEOQHmkIM7GVl4utMzwf2y3HjNh5Nm9kuSmFi9YJ4Ltac5ej+1Mbv/Y32G8Tm8Ujp22Yo1vZoNqJTCcR6SDAHTqrji8JEKGiBToWw3RJic/fbJEnE6JDiN9YxFaGowcWFAP2IT0hHt2OOeTAYBzWQjv4qnnFoeAQj3zVqHBymnaPz0jeNBug4IvEhyoAwYQd719sbEizaERgNZeavWUy7kIfeDulvGUZ5BqIriT762Zp1/0Egsjf5gzDrNJP0m9fZFvqZX1ubCiQZCDGmK2K+xHPR4kOkV9FhIqHhPhGVTx26Fa5AdkoOhRhZ3VDHMXSDTykSUbLUfdllJmXzM82nZKMZTXjcF9ngflsO8kBcEb/5iGzK0pb3BOTCZVOQec3h7DktxpdNd4XzOfMXlcnzRDGWPtnxFsMoHEukZylxESVA74Bc4pW+W8YZ333MQeWgq2Ti1DoLyh41SPwKXA+KGWK7GJ347hgRuP1o3L4myVIx2yE6MCbJndRMWkYOxiYcASZjNCrz4CeIyy5NzWQ=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  apt: true
  directories:
  - node_modules
before_install:
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/lint.sh
before_script:
- "./.build_scripts/lint.sh"
- npm test
script:
- npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: ".build_scripts/deploy.sh"
  on:
    branch: "${DEPLOY_BRANCH}"
