language: node_js
node_js:
- '4'
env:
  global:
  - CXX=g++-4.8
  - DEPLOY_BRANCH=master
  - secure: g+dxH97BqFQEbuyaA4TnRJ961sVBiaoHBfd9iN3sMXuBZ5lTz7aeppH1V/bC2HH4H3/jTQQbn4gxVPeSyPSPIdVYgfAgQ1NebQ3gmZjoDroLPubSSvpChIV8tLJaCZIbq4LBmgm0BsJ90HMwGz6q9sid11jlYMYyAY0pCfshj8HK9MmLWleaUlWtaTecgZ1UvkmDV8/JZpRcdJ6OXbbhJiwqun15ieAcS7bpzS9XaVEEzlFQdDLcgNO0MZk+xtJl6jFA7L1lMfuTxSRbRA7WpAxzyAlLWu0ZT2XjVgpOCm38kehipV6F5s7ABgqYBLKaF80CaIqtlMQh07aze62/pfZPR8nB1OAvm7K4F3TfWw+s3tHPSLfcrK64vNmBTHHPdGMlG7n43n+f0hWDfNYd1tUS8fTW+u5s2GHjmnr19Yq4X4B6FmDqqXM0HEFG8LO01pLvGWNA5WD6sptlEMruyq+qzWwV+zpp+eVqKRkrXxE/u7qKwRVahkrzC+FM52M++zbWD8/6DS2u/G+jYSoMkYl7p+1QEayCyLww1OjDLRG7lNS1bweU1OdzwcOolv3zxlf6SNzKb8FM1UfAtuvxEagKW4jlRkr452I7ZhH21UQhkp5SgDpb6yWWC4vrc7O+XsS/fv8vX8/GagimQF9BBdgruJFe4zx1TCw/+DFpTCo=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  apt: true
  directories:
  - node_modules
before_install:
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/lint.sh
before_script:
- "./.build_scripts/lint.sh"
- npm test
script:
- npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: ".build_scripts/deploy.sh"
  on:
    branch: "${DEPLOY_BRANCH}"
